# Generated by Django 3.2.12 on 2022-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autograder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="autograder.Course"
            ),
        ),
    ]
